### ISSUE TITLE
error when signing with RS256: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by arikalfus** [hokaccha/node-jwt-simple#21]
I get this stack trace when signing a token with a non-default (yet supposedly supported) signing algorithm:
`jwt.encode(payload, secret, 'RS256')`

This is the stack trace, modified to remove my personal directory path:

```
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
   at Error (native)
   at Sign.sign (crypto.js:327:26)
   at sign (<path>\node_modules\jwt-simple\lib\jwt.js:155:57)
   at Object.jwt_encode [as encode] (<path>\node_modules\jwt-simple\lib\jwt.js:125:17)
   at Object.gen [as generateToken] 
<rest of my application's stack trace>
```

I've verified that every other signing algorithm succeeds, except for RS256.

**Comment by yunfan141** [comment]
same problem with you!
other algorithms succeed!
