### ISSUE TITLE
Security sniff token

### ISSUE THREAD

**Issue by edouardbrossette** [hokaccha/node-jwt-simple#24]
Without change in the payload,  the token key will remain identic over time. If an attacker sniff the token, he will keep access. Propose to add an automatic dynamic var in the payload. For example  an iat ("issued at) base on time. This will make the token string change, but this is not enough because the old key will still validate. The best way is to make a Server validation that the token received is really the last one who as been emit. unfortunately many integration skip this essential part. 
So maybe you can also patch this integration weakness with a default expiration date. If you base the expiration Date on a Date type, not on timeout integrer it can replace the IAT because it will different every time.

At the end, i suggest to add an facultative expiration duration (millisecond ) param  to the sign function.
If not use  : go to default X ms
then convert the var in a Date type expiration and add to the payload.

**Comment by justhamade** [comment]
https://github.com/auth0/node-jsonwebtoken includes an iat by default.

**Comment by NathanRSmith** [comment]
You are free to put whatever information you want in the payload, including an iat.
