### ISSUE TITLE
Error Handling??

### ISSUE THREAD

**Issue by somsharan** [hokaccha/node-jwt-simple#29]
It would be better if we had better error handling process.
Instead of throwing the error we can return it in the response to function call.?

**Comment by iarroyo5** [comment]
This pull request could solved this problem.
https://github.com/hokaccha/node-jwt-simple/pull/33

**Comment by Incubatio** [comment]
@somsharan How is putting error in response bringing being better error handling ?
Everything is synchronous, throwing an Error in a case like this seem pretty standard.

@iarroyo5 #33 isn't solving somsharran request.

**Comment by hokaccha** [comment]
> Everything is synchronous, throwing an Error in a case like this seem pretty standard.

+1

I think returning error object is not standard in JavaScript. You should use `try-catch`.
