### ISSUE TITLE
How to use in Meteor?

### ISSUE THREAD

**Issue by MastaBaba** [hokaccha/node-jwt-simple#30]
The meteor package at https://atmospherejs.com/outatime/jwt-simple has an example that, when implemented, returns:

Exception from Tracker afterFlush function:
ReferenceError: require is not defined 

How to use this inside Meteor?

**Comment by alexjab** [comment]
Hi @MastaBaba This issue is quite old, and has not been updated for over a year. Can I close it ?

**Comment by MastaBaba** [comment]
Hmmmm. I suppose. I sadly don't remember how I dealt with that. :/
I'll close this now.
