### ISSUE TITLE
how to alter header

### ISSUE THREAD

**Issue by enVolt** [hokaccha/node-jwt-simple#46]
I want to alter the header of jwt token. Is it possible to do this using this library?
My use-case is I've two types of token, and I want to distinguish between them. Last resort is to include a key in payload itself, which I don't feel comfortable with.

**Comment by alexjab** [comment]
I think you should put it in the token payload anyway (in the "claims"). That's what the payload is for, IMHO.

According to the RFC, the JWT header is meant for cryptographic information: 
```
The contents of the JOSE Header describe the cryptographic operations
applied to the JWT Claims Set.
```

Regarding the payload:
```
Claim Names can be defined at will by those using JWTs.  However, in
order to prevent collisions, [...] the definer of the name or
value needs to take reasonable precautions to make sure they are in
control of the part of the namespace they use to define the Claim
Name.
```

You can get a list of registered claim names [here](https://tools.ietf.org/html/rfc7519#section-4.1). Just don't use one that's already registered, and you should be fine with any implementation of JWT.

Source: https://tools.ietf.org/html/rfc7519

**Comment by alexjab** [comment]
Hi @enVolt Can I close this issue ?

**Comment by enVolt** [comment]
I went with last resort approach. Thanks. This pull request can be closed now.
