### ISSUE TITLE
Decode tokens without secret

### ISSUE THREAD

**Issue by Univac1107** [hokaccha/node-jwt-simple#47]
You are supposed to be able to decode the token without the secret. The token is not encrypted, it is just signed. I should be able to get the token's contents, and to verify the signature validity using the secret. independently. Am I missing something?

**Comment by bdunn44** [comment]
I'm pretty sure the JWT spec states the payload is base 64 encoded, but I'm just getting started with JWT and jwt-simple. It should be trivial to decode it yourself (and add it to this module at some point).

**Comment by alexjab** [comment]
Hi,

the third option of `jwt.decode` is `noVerify`. If set to `true`, it just returns the payload as an `Object`.

https://github.com/hokaccha/node-jwt-simple/blob/master/lib/jwt.js#L58

That said, you can get an `Object` from the token very easily by hand:
```
console.log(JSON.parse(new Buffer(token.split('.')[1], 'base64').toString()));
```

**Comment by alexjab** [comment]
Hi,

this issue has been opened for quite some time, and has not been updated since then, so I'd like to close it, if you don't have anything to add / ask.

Thank you,

Alex

**Comment by alexjab** [comment]
I'm closing the issue, feel free to re-open it if you need anything else.
