### ISSUE TITLE
Order of header fields

### ISSUE THREAD

**Issue by 4nduril** [hokaccha/node-jwt-simple#49]
I know that properties of objects do not have a deterministic order (in theory). But when I `JSON.stringify` that object I have a relevant order of bytes or characters. Which becomes a problem when hashing that string. Suddenly,
```
{
  typ: "JWT",
  alg: "HS256"
}
```
is not same as 
```
{
  alg: "HS256",
  typ: "JWT"
}
```
In a current project I have the problem that we have JWTs created by some Java classes and I want to use jws-simple to make the Javascript counterpart. Unfortunately, the header fields are in exactly the opposite order than here in this JS code which renders the package unusable for us without patching.

Does anyone have an idea how to come over that?

**Comment by alexjab** [comment]
I don't think there should be any problem. When checking the signature, the library always uses the raw input token which is a base64ed stringified Object, not the Object itself.

https://github.com/hokaccha/node-jwt-simple/blob/master/lib/jwt.js#L96

If this is not clear, you can provided a more detailed use case.

**Comment by 4nduril** [comment]
Ok, so given the to Object literals above. Let's say the first is called `a` and the second is `b`. Then I do:
```javascript
const jsonA = JSON.stringify(a);
const jsonB = JSON.stringify(b);
```
then
```javascript
jsonA === jsonB;
// false
```
and more importantly:
```javascript
const sigA = crypto.createHmac(method, key).update(jsonA).digest('base64');
const sigB = crypto.createHmac(method, key).update(jsonB).digest('base64');
sigA === sigB;
// false
```

This is a real problem.

**Comment by alexjab** [comment]
I'm not sure I understand what you are trying to prove with the last piece of code. Do you have a real-life system that operates this way ? Because that is not how signature validation works.

Here is a simple example:
Let's say `jsonA / sigA` and `jsonB / sigB` are produced by two different implementations, on two different systems, and they both need to be validated in the same auth system (here, the function `isValid`).

```
const crypto = require('crypto');

const jsonA = JSON.stringify({ foo: 'bar', bar: 'foo' });
const jsonB = JSON.stringify({ bar: 'foo', foo: 'bar' });

const sigA = crypto.createHmac('sha256', '__secret__').update(jsonA).digest('base64');
const sigB = crypto.createHmac('sha256', '__secret__').update(jsonB).digest('base64');

function isValid(token, signature) {
  return signature === crypto.createHmac('sha256', '__secret__').update(token).digest('base64');
}

// Here is the actual validation done by our auth system
console.log(isValid(jsonA, sigA));
// => true
console.log(isValid(jsonB, sigB));
// => true

// These are just random checks, they should not be used to authenticate a token
console.log(jsonA === jsonB);
// => false
console.log(sigA === sigB);
// => false
```

**Comment by 4nduril** [comment]
Oh my. You're totally right, of course. I had real big knot in my brain. Thank you very much for untying it.

**Comment by alexjab** [comment]
=)

That said, you've raised a valid and interesting point about "signing" Objects in general.
