### ISSUE TITLE
Default Expiration Time

### ISSUE THREAD

**Issue by aroramayur** [hokaccha/node-jwt-simple#50]
Does this offer a default 'exp' ? How does one set it  (both iat and exp ). I can set iat easily. How do I set 'exp' to say 5 hours after 'iat' ? There's just documentation , no explanation.

**Comment by alexjab** [comment]
Hi, 

1/ There is no default `exp`,
2/ With native js:
```
console.log({
  iat: Math.round(Date.now() / 1000),
  exp: Math.round((Date.now() + 5 * 60 * 1000) / 1000)
});
```
With moment.js:
```
console.log({
  iat: moment().unix(),
  exp: moment().add(5, 'hours').unix()
});
```

BTW, what you are asking is vanilla js, not actually specific to jwt.

Here is more information on the timestamp format for those fields:
https://tools.ietf.org/html/rfc7519#section-2

You are right about the documentation, these could do with a little help.

**Comment by mrvipin** [comment]
how to add expires time in jwt-simple.

**Comment by kmgilbert100** [comment]
^

**Comment by suvradip** [comment]
@mrvipin , you need to set 
jwt.encode({ nbf: Date.now(), exp: Date.now() + 900000}, "secretKey");

**Comment by jakoblorz** [comment]
@suvradip does this then mean that the token expires **after 900 seconds**? because in the decode function exp will be **multiplied by 1000** - that doesn't make sense to me

**Comment by alexjab** [comment]
According to the RFC, `nbf` and `exp` must be POSIX timestamps (in seconds), thus the example provided by @suvradip is incorrect (not false _per se_, the token will just be valid and expire in the year ~50K).

**Comment by jakoblorz** [comment]
@alexjab @suvradip so the right snippet would be
`jwt.encode({ nbf: (Date.now() / 1000), exp: ((Date.now() / 1000) + seconds) }, 'key');` where `seconds` represent the duration until expiration in seconds?

**Comment by alexjab** [comment]
Seems about right. I'd use moment.js to do Date manipulations, though. You can see my first example.

**Comment by alexjab** [comment]
Also, in your case `nbf` is purely informative, and in no way necessary to implement expiration.

**Comment by alexjab** [comment]
Hi all, 

@aroramayur Can I close this issue ?

**Comment by aroramayur** [comment]
Sure

Thanks
Mayur Arora
