### ISSUE TITLE
jti?

### ISSUE THREAD

**Issue by izanagi1995** [hokaccha/node-jwt-simple#56]
Hello,

Can I use `jti` to revoke tokens? If yes, can I set it and read it in your module?

Thank you

**Comment by alexjab** [comment]
Just add a `jti` claim in the payload. From what I've understood, `jti` is just a standard claim name for a unique identifier (I guess you could have `id`, `_id`, `uid`, etc...).

About revocation, I guess you'll have to implement that logic server-side, and I don't think it should be the responsibility of a `jwt` module.

**Comment by alexjab** [comment]
Hi @izanagi1995 Can I close this issue ?

**Comment by izanagi1995** [comment]
Yes!

**Comment by alexjab** [comment]
Thank you !
