### ISSUE TITLE
how to pass jwt token using postman

### ISSUE THREAD

**Issue by gutasaputra** [hokaccha/node-jwt-simple#58]
hi, im new using jwt auth.
i already generated jwt token by simply passing username and password using postman.
but i dont know how to pass the token that i have to access my restricted page via postman. 
ideally, we can only access this page, if we already have the token.

i try like this
<img width="960" alt="screen shot 2017-01-19 at 4 01 01 am" src="https://cloud.githubusercontent.com/assets/1556126/22082824/f14031b2-ddfb-11e6-8afd-0c5e0d75bfb1.png">

but i cant see the restricted page. 
in this case http://localhost:3000/user

pls help me to fix this issue.
thank you.

**Comment by alexjab** [comment]
1/ The controller for your restricted page must implement a way to decode the token (usually, your routes will be protected by an authentication middleware),
2/ You must send your token in accordance with the way you intend to decode it,
3/ Usually the token is sent in the headers, but sometimes it is also passed as a url query parameter (according to the RFC http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html#authz-header).

Example:
In the request: add a header with key `Authorization`, and value `Bearer <token>`.
In the authentication middleware, read the token:
```
(req, res, next) => {
  const authorization = req.get('authorization');
  const token = authorization.split('Bearer ')[1];
  ...
}
```

Fine tune this code to your need.

**Comment by gutasaputra** [comment]
hi, thanks for the reply.
actually, i follow this tutorial : 
https://blog.jscrambler.com/implementing-jwt-using-passport/

then i mix it with your solution.
with your code, i can get the token that i generated with jwt.

in my restricted page, i can get my token. 
but everytime i use this method,  auth.authenticate()
i will always got Unauthorized error msg.

i dont understand. can you pls help me to fix this issue?

**Comment by shanemcgraw** [comment]
Hey @gutasaputra. I ran into the same issue myself and just figured it out. The 401 status could be due to a couple of things: 

1) It could be that the signed JWT you're passing is expiring before you can check it with postman, and you simply need to set the expiration param to an obnoxiously longer time for testing, like so: 
         `var payload = {
              id: userObject.id,
              exp: 100000000000000000000
            };`
2) It could also be that you aren't sending the JWT in postman correctly. Based on your screenshot, it looks like you're not including the "JWT" prefix to the Auth header. For JWTs, it should look like this:

<img width="930" alt="screen shot 2017-02-25 at 3 56 03 pm" src="https://cloud.githubusercontent.com/assets/10692718/23335865/f2682d76-fb72-11e6-8802-3157da29c622.png">

Fixing one (or both) of those issues should enable JWT auth to work in your app. Good luck!

**Comment by alexjab** [comment]
Hi,

this issue has been opened for quite some time, so if there is nothing more you would like to ask or add, I'd like to close it.

Thank you,

Alex

**Comment by alexjab** [comment]
I'm closing the issue, feel free to re-open it if you need anything else.

**Comment by tekkenking** [comment]
Am running wampserver 3.0.9
Apache 2.4.27
PHP 7.1.8

Implementing all the suggested header solutions in htaccess, still not working..

Still looking for solution. Please

**Comment by GuidoVarga** [comment]
Hi. I suppose you already solved it. Anyway, I bring the solution for anyone who needs it.
Your header should look like this.

![header](https://user-images.githubusercontent.com/21971429/44043667-cbc1b904-9ef9-11e8-994f-95214f38eaa2.png)

**Comment by KeitelDOG** [comment]
I was using an android package "codepath android-oauth-handler", and I just added a header to the request `getClient().addHeader("Authorization", "Bearer " + bearerTokenString);` , and it worked with the `auth:api` middleware.

**Comment by Sporky023** [comment]
@GuidoVarga I am using a header like that, specifically in this format:

```
Authorization:  Bearer <my.jwt.string>  
```  


and postman is failing on a GET request with the error `Error: The header content contains invalid characters`.  

If I remove the dots from the JWT, Postman sends the request just fine and a breakpoint on my server is reached.  

The options I'm looking at are:  

1.  Reconfigure Postman to stop complaining about dots in the header value  

2.  Base-64 encode my JWT in the client, then decode on the server.  

Do you know how to configure Postman for option 1?  The way you described it, it sounds as if the strategy as worked for you.  Has it?

Thanks in advance.

**Comment by Sporky023** [comment]
I solved my problem immediately above:  The JWT value I was pasting into Postman's environment included a newline character.  Removing that solved the problem.  

The error message, `The header content contains invalid characters` is composed not by Postman, but by the underlying **request** library.  

See https://github.com/request/request/issues/2632#issuecomment-300392528

**Comment by GuidoVarga** [comment]
@Sporky023  Great, I'm glad you found the solution. Newlines can generate problems that are difficult to detect

**Comment by iubhatt17** [comment]
I am facing same problem but it is vice versa for my case.Browser is showing unauthorized error in console and when I pass token in postman it is showing propper result.I don't know why my browser is not taking "Authorization" header.Kindly help me with this isssue.
