### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by hokaccha** [hokaccha/node-jwt-simple#64]
I created this module five years ago. At that time I needed this module, but now it is not. However, there are many people who are using this module.

Since it's difficult for me to continually improve in the future, I'm looking for maintainer. I think @alexjab is good. He constantly responded to issues and reviewed pull requests.

@alexjab Are you interested?

**Comment by alexjab** [comment]
@hokaccha : sorry for the delay, I had a lot on my plate at work =)

Why not, that could be an interesting experience. That said, I'd like you to still stick around a bit in case I have questions and suggestions =)

**Comment by hokaccha** [comment]
@alexjab Thank you for your cooperation. 

> That said, I'd like you to still stick around a bit in case I have questions and suggestions =)

Sure, I will.

I added you to the collaborator in this repository. Thank you.
