### ISSUE TITLE
Unable to use RSA keys

### ISSUE THREAD

**Issue by nitinmukesh** [hokaccha/node-jwt-simple#65]
Hello,

I integrated JWT token in my project and it is working fine. The token is generated using jwtSecret variable which contains simple string. I want to use RSA key instead of simple string.

> "jwt-simple": "^0.4.1"
> node -v 7.6.0

I generated key using

```
openssl genrsa -out secure.rsa 1024
openssl rsa -in secure.rsa -pubout > secure.rsa.pub
```

```
import jwt from "jwt-simple";
import fs from "fs";

module.exports = app => {
    const cfg = app.libs.config;
    const Users = app.db.models.Users;

    const publicKey = fs.readFileSync('secure.rsa.pub');
    const privateKey = fs.readFileSync('secure.rsa');
    app.post('/token', (req, res) => {
        if(req.body.email && req.body.password) {
            const email = req.body.email;
            const password = req.body.password;
            Users.findOne({where: {email:email}})
                .then(user => {
                    if(Users.isPassword(user.password, password)) {
                        //var token1 = jwt.sign({id: user.id}, privateKey, {algorithm: 'RS256'});
                        //console.log(token1);
                        console.log(privateKey);
                        //var abc = jwt.encode(payload, privateKey, false, {algorithm: 'RS256'});
                        //console.log(abc);
                        const payload = {id: user.id};
                        res.json({
                            token: jwt.encode(payload, cfg.jwtSecret)
                        });
                    } else {
                        res.sendStatus(401);
                    }
                })
                .catch(error => {
                    res.sendStatus(401)
                });
        } else {
            res.sendStatus(401)
        }
    });
};
```

The issue is as soon as I uncomment one of the following Approach it start to throw error "Unauthorized". I am not sure how to fix this.

/*Approach 1*/
//var token1 = jwt.sign({id: user.id}, privateKey, {algorithm: 'RS256'});
//console.log(token1);

/*Approach 2*/
//var abc = jwt.encode(payload, privateKey, false, {algorithm: 'RS256'});
//console.log(abc);

**Comment by alexjab** [comment]
Hi,

my best guess is because you made in mistake when calling `jwt-simple` in your two approaches. The parameters you passed actually belong to the module `jsonwebtoken`, not `jwt-simple`. What you would need to do is `jwt.encode(payload, cfg.jwtSecret, 'RS256')`.

The reason you get a 401 is because you `catch` handles errors by returning a 401. IMHO, this is an anti-pattern, and should return a 500, plus log an error in your error reporting tool.

**Comment by alexjab** [comment]
Hi @nitinmukesh Can I close this issue ?

**Comment by alexjab** [comment]
I'm closing the issue, feel free to re-open it if you need anything else.
