### ISSUE TITLE
Expiration time. Is not working properly?

### ISSUE THREAD

**Issue by Lzok** [hokaccha/node-jwt-simple#74]
Hello all. Like the title said, I am experimenting problems with the token's expiration time. I red the related issue #50 and tried the examples there but they don't work for me (I think). This is what I am doing:

```
const payload = {
    id: user.id
};
const options = {
    nbf: moment().unix(),
    exp: moment().add(2, 'hours').unix()    // I want to refresh the token every 2 hours.
}
const token = jwt.encode(payload, cfg.auth.jwtSecret, 'HS256', options);
```

Am I doing something wrong?

Cheers.

**Comment by alexjab** [comment]
Hi thanks for the inquiry =)

`options` (last parameter) does not take payload claims. You should put them directly in the payload.

Example:
```
const payload = {
    id: user.id,
    nbf: moment().unix(),
    exp: moment().add(2, 'hours').unix()    // I want to refresh the token every 2 hours.
};

const token = jwt.encode(payload, cfg.auth.jwtSecret, 'HS256');
```

BR,

Alex

**Comment by Lzok** [comment]
@alexjab Yes, you are right! Now it's working.

You can close the issue, thanks.
