### ISSUE TITLE
[DeprecationWarning] Fixed Buffer deprecation warning

### ISSUE THREAD

**Issue by emmanuelbuah** [hokaccha/node-jwt-simple#93]
Running in node 10+ raises 
```
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
From https://nodejs.org/api/buffer.html#buffer_new_buffer_string_encoding, new Buffer() has been deprecated. Please update the code per recommended fix.

**Comment by hokaccha** [comment]
fixed by https://github.com/hokaccha/node-jwt-simple/pull/89
